apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: name

  replicas: 3
  template:
    metadata:
      labels:
        app: name
    spec:
      volumes:
        # - name: name-volumes
        #   hostPath: #the virtual machine[Node specific]
        #     path: /data #more like a bind mount
        #     type: DirectoryOrCreate
          # emptyDir: {} [pod specific]

          #csi[interface with NFS(network file system{EFS for amazon})]

        - name: my-own-volumes
          persistentVolumeClaim:
            claimName: host-pvc

      containers:
        - name: api
          image: ademolaolutomiwa4real/kub-api
          volumeMounts:
            - mountPath: /usr/src/app/src/logs
              name: my-own-volumes
          env:
            - name: STORY_FOLDER,
              # value: 'story folder'

              valueFrom:
                configMapKeyRef:
                  name: environment-variable-env
                  key: createdKey

            
          # livenessProbe:
            # httpGet:
            #   path: /
            #   port: 3000
            #   # headers:
            # periodSeconds: 10 #seconds
            # initialDelaySeconds: 5

        - name: auth 
          image: ademolaolutomiwa4real/kub-auth
          # livenessProbe:
          #   httpGet:
          #     path: /health-check
          #     port: 3000
          #     # headers:
          #   periodSeconds: 10 #seconds
          #   initialDelaySeconds: 5
