apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-persistence-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: FileSystem #FileSystem, Block
  storageClassName: standard
  hostPath:
    path: /data
    type: DirectoryOrCreate
  accessMode:
    - ReadWriteOnce #can be mounted as a read write volume by a single node[multiple pod]
    # - ReadOnlyMany #can be mounted as a read only volume by a multiple node
    # - ReadWriteMany #can be mounted as a read write volume by multiple nodes

  # capacity:
  #   storage: <Size>
  # volumeMode: Filesystem
  # accessModes:
  #   - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
