apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: name
  ports:
    - protocol: TCP
      port: 3001 #to running machine
      targetPort: 3001 #from container
      name: http
  type: LoadBalancer # for multiple pod in the same node[ClusterIP, NodePort, LoadBalancer]

--- # must be three

apiVersion: v1
kind: Service
metadata:
  name: another
spec:
  selector:
    app: name
  ports:
    - protocol: TCP
      port: 3000 #to running machine
      targetPort: 3000 #from container
      name: http
  type: LoadBalancer #

# service should come before deployment

